trigger:
- main

pool:
  name: linux-hosted-agent

steps:
  - script: echo hello, World!
    displayName: 'Run a one-line script'
    
  - script:
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - script: uname -a
    displayName: "OS Info"

  - script: whoami
    displayName: "Current User"

  - script: df -h
    displayName: "Disk Usage"
